### ISSUE TITLE
On mobile, the hero photo should be resized and placed under "Watch Seasons 5 Now" 

### ISSUE THREAD

**Issue by andresmh** [andresmh/remixingblackmirror#3]
Currently, the photo just disappears in smalls screens.

**Comment by sarohabhawna** [comment]
responsiveness has been done, please review

**Comment by andresmh** [comment]
when i use the responsive feature in Google Chrome I see that the hero image is not showing up and there's a string that says "black mirror" in tiny font. that text is not needed
![image](https://user-images.githubusercontent.com/26597/60531908-e617b000-9cb0-11e9-83c6-4cedaf014fe7.png)
